### ISSUE TITLE
Needs a new release for the documented `region` option to work

### ISSUE THREAD

**Issue by blueimp** [buildkite-plugins/ecr-buildkite-plugin#14]
Hi, the region option does not work with the latest release version (v1.1.3).
What works is the undocumented  (*and deprecated?*) `registry_region` option.

Neither the master documentation nor the [v1.1.3 documentation](https://github.com/buildkite-plugins/ecr-buildkite-plugin/blob/v1.1.3/README.md) mention `registry_region`.

I think the simplest solution would be to release a new version and recommend to use this new tagged version instead.

**Comment by toolmantim** [comment]
Sorry about that @blueimp! You're totally right about just putting out a new release — looks like it was the best thing. That's all done now.

**Comment by blueimp** [comment]
Thanks!

Minor nitpick: The second code example still uses `ecr#v1.1.3` in the master README.

**Comment by toolmantim** [comment]
Oh, good catch! Thanks, all fixed now.
