### ISSUE TITLE
Windows: "Expected buildkite-agent to be in the form x.y.z"

### ISSUE THREAD

**Issue by codykrieger** [buildkite-plugins/ecr-buildkite-plugin#25]
Attempting to use this plug-in on a Windows-based agent appears to result in the following:

```
Running plugin github.com/buildkite-plugins/ecr-buildkite-plugin#v1.1.4 pre-command hook

> C:\buildkite-agent\plugins\github-com-buildkite-plugins-ecr-buildkite-plugin-v1-1-4\hooks\pre-command
Expected buildkite-agent to be in the form x.y.z
🚨 Error: The plugin github.com/buildkite-plugins/ecr-buildkite-plugin#v1.1.4 pre-command hook exited with status 1
```

I'm running `buildkite-agent` version 3.5.2 on Windows Server 1803. The AWS CLI and Git for Windows are installed, and with the exception of some custom tags, the `buildkite-agent` configuration file is the stock one generated by the [automated PowerShell installer script][installer-script] (so `cmd.exe` is the default shell, etc.).

[installer-script]: https://raw.githubusercontent.com/buildkite/agent/master/install.ps1

**Comment by jjmilburn** [comment]
Have you run into this issue in newer versions of the plugin, e.g. `ecr#v2.0.0`?

**Comment by codykrieger** [comment]
@jjmilburn I've since crafted an alternate solution, so I'm not sure.

**Comment by smclendening** [comment]
For anyone else who gets this in the future - I got this error, and it turned out the issue was my buildkite-agent's `$PATH` did not include the aws-cli executable. It looks like this error will occur if buildkite-agent doesn't have access to the aws-cli, or if its aws-cli version is too old.

**Comment by pzeballos** [comment]
Hi folks! We did several changes to the agent, particularly for Windows. We couldn't reproduce this issue, but if you are still having problems can you open a new one with all the details? thanks!
