### ISSUE TITLE
Docker login command written as output

### ISSUE THREAD

**Issue by scottybrisbane** [buildkite-plugins/ecr-buildkite-plugin#28]
Hi there! We are extensive users of this plugin and like it a lot :) 

We did recently notice something, however, that has caused us to pin all our pipelines to version 1.1.4. We noticed that the current master branch version of the plugin `echo`'s the docker login command, meaning the token it uses is displayed in our BuildKite job logs. For us this isn't ideal as it would allow a developer with BuildKite access to authenticate on their dev machine to the respective ECR repository for up to 12 hours after the build step was run.

Would it be possible to either remove the `echo` or put it behind a configuration option so we can hide it?

**Comment by lox** [comment]
Hmmmm 🤔 That looks to be unintentional, and introduced by me. I completely agree that it's a huge issue. I'll get a fix out immediately.

**Comment by lox** [comment]
Released in https://github.com/buildkite-plugins/ecr-buildkite-plugin/releases/tag/v1.2.0 @scottybrisbane. Thanks for the heads up!

**Comment by scottybrisbane** [comment]
Thanks for the quick fix @lox!
