### ISSUE TITLE
Account ids inconsistent in the readme

### ISSUE THREAD

**Issue by viraptor** [buildkite-plugins/ecr-buildkite-plugin#30]
Readme seems to use two different forms for the same option:

In the example:
```
 account_ids: "0015615400570"
```
Later:
```
Options
...
account-ids (optional)
```

A consistent `-` or `_` would be great :)

**Comment by keithduncan** [comment]
Hi @viraptor the [agent](https://github.com/buildkite/agent/blob/ef331a35ca29079cb77c9ced402b3c898dd48273/agent/plugin/plugin.go#L201-L214) actually supports both formats but you’re absolutely right the README does look confusing! I’ll fix that up now 😄
