### ISSUE TITLE
Confused about default AWS region

### ISSUE THREAD

**Issue by smclendening** [buildkite-plugins/ecr-buildkite-plugin#34]
This is the documentation for the `region` option:
> Set a specific region for ECR, defaults to the current

What does **current** mean here? My guess was that it would use whatever I had configured in my `~/.aws/config` file. But I wasn't able to get this plugin to work until I specified the option in the pipeline config. Not a big deal, I'm just curious how this works.

**Comment by lox** [comment]
Fair point, sorry it was confusing! Without a specific region specified it will just depend on what the behaviour of the `aws` command is without a region specified, which is to look in your config or the environment. 

It would be interesting to see what the output of `aws configure list` shows as a pipeline command, I wonder if the config file is in the right place?

**Comment by keithduncan** [comment]
The behaviour of this option has been [clarified](https://github.com/buildkite-plugins/ecr-buildkite-plugin/commit/f2d378f9fb90923248e2a475453a015243314196) since this issue was opened. Thank you for opening this issue, and please let us know if we can help further! 😄
