### ISSUE TITLE
Use of `mapfile` introduces bash4 dependency making local runs difficult on macOS

### ISSUE THREAD

**Issue by pdbreen** [buildkite-plugins/ecr-buildkite-plugin#46]
`!/bin/bash` on macOS is still 3.2.x and doesn't include mapfile command.  This prevents `bk local run` on macOS with version 2.1 of this plugin.

**Comment by ryansdwilson** [comment]
hey @pda any thoughts on this issue? we've gotten really hung up on this issue. Even when you follow kkolk's awesome advice and use his fork with the changes there are issues with all sorts of local deps once you change the shell. Do you see a future where mapfile is eliminated or where some solution for installing a newer version of bash will work? Thanks for your help!

**Comment by pda** [comment]
Maybe we can use https://github.com/dosentmatter/bash-mapfile-shim

**Comment by lox** [comment]
There are some great suggestions on https://github.com/koalaman/shellcheck/wiki/SC2207 on how to avoid `mapfile`, my preference would be to just ditch `mapfile` usage. It's replaceable in my experience.

**Comment by pda** [comment]
Hah, I just realised it was me that switched this to `mapfile` based on shellcheck advice:
https://github.com/buildkite-plugins/ecr-buildkite-plugin/commit/da2472ff784ab6ed427f9827d79bb10ac11c0060

But yep, I'll open a PR switching this, and the other instance, back to bash 3.x compatible code.
