### ISSUE TITLE
Document permissions required for this repo

### ISSUE THREAD

**Issue by chloeruka** [buildkite-plugins/ecr-buildkite-plugin#52]
This plugin requires access to IAM permissions for the ECR repo(s) being used, it'd be nice to briefly note in the README what it'll need, or link to the [relevant part of the AWS docs for ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_id-based-policy-examples.html)

**Comment by sj26** [comment]
I've added a few words to the README in https://github.com/buildkite-plugins/ecr-buildkite-plugin/commit/300703c75eaa5a797e0d0b00459fed45ac18e080
