### ISSUE TITLE
ECR login hangs forever – sporadically

### ISSUE THREAD

**Issue by TSMMark** [buildkite-plugins/ecr-buildkite-plugin#66]
I posted in buildkite community slack as well but it was not addressed. https://buildkite-community.slack.com/archives/C7KTYPZ5W/p1624281329003200

This is really impacting velocity as CI builds randomly hang forever.

```
Running plugin ecr environment hook 0s
[2021-06-22T16:12:01Z] $ /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-ecr-buildkite-plugin-v2-3-0/hooks/environment
Authenticating with AWS ECR 
[2021-06-22T16:12:02Z] ^^^ Authenticating with AWS ECR in us-west-2 for 12345 :ecr: :docker:
```

^ It will then remain there for hours — until the build is stopped manually, or timeout seconds for the step is reached.

Appears to be coming from these lines: https://github.com/buildkite-plugins/ecr-buildkite-plugin/blob/a7e99dc4da50fa8dfc5a520b85ec8a28b6a7087a/hooks/environment#L146-L150

It is intermittent and seemingly random. Sometimes it hangs, sometimes it moves along instantly. We are not doing anything on our end that should impact this.

---

After hanging forever, if the step or build is restarted, it has a chance of succeeding.

---

For buildkite staff, here's an example of a build that I killed after hanging there for 13 minutes https://buildkite.com/vydia/web/builds/8804#450f8bce-7c43-4bb9-ab2f-cbff1c4ecb6c Then upon rebuild, it has continued along without any issues https://buildkite.com/vydia/web/builds/8805#514ac531-d26a-4c78-9fd8-e32285f6b76f — Both builds are for the same commit and with no changes in configuration, and no difference between them.

**Comment by TSMMark** [comment]
Paula from buildkite support helped me solve this.

> it suggests this could happen in an Out Of Memory situation https://github.com/moby/moby/issues/42437

We reduced number of agents per instance (aws stack) and now we don't seem to have the issue.

**Comment by keithduncan** [comment]
Hi @TSMMark from what I can tell this issue is fixed and was a systems issue on the hosts running your buildkite-agents rather than a bug in this plug-in. Let us know whether you are still experiencing this issue and we’ll take another look with you, thanks!
