### ISSUE TITLE
Feature Request: Retry `aws ecr get-login`

### ISSUE THREAD

**Issue by meganemura** [buildkite-plugins/ecr-buildkite-plugin#7]
Hi, there.
I am facing the following error along with 150 parallel agents with ecr-buildkite-plugin#v1.1.2.

```
Authenticating with AWS ECR | 6s
  | An error occurred (ThrottlingException) when calling the GetAuthorizationToken operation (reached max retries: 4): Rate exceeded
  | 🚨 Buildkite Error: The global pre-command hook exited with a status of 255
```
http://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html

I couldn't find how to increase retry times of `aws ecr get-login` command.
How about implement sleep and retry if `aws ecr get-login` is failed.

**Comment by lox** [comment]
Makes a lot of sense!
