### ISSUE TITLE
1.1.3 release

### ISSUE THREAD

**Issue by envatopoho** [buildkite-plugins/ecr-buildkite-plugin#8]
Any chance of cutting a 1.1.3 release with the region selection stuff  from [this](https://github.com/buildkite-plugins/ecr-buildkite-plugin/commit/7d8e19883a9f4b2bfd4ad6859cdeac36087c5742) in there?

Thanks!

**Comment by lox** [comment]
Done!

**Comment by envatopoho** [comment]
Thanks!

**Comment by envatopoho** [comment]
@lox It looks like it was tagged as `1.1.3` not  `v1.1.3`  which tripped me up.  I altered my code but thought i'd let you know for consistency 😄

**Comment by lox** [comment]
🤦‍♂️ 

Not at my finest today.

**Comment by lox** [comment]
I will push the v1.1.3 version and delete the incorrect one if that is ok.

**Comment by envatopoho** [comment]
Sure - no worries 👍

**Comment by lox** [comment]
Done.
